version: "3.9"
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./start.sh:/app/start.sh
    entrypoint: ["/bin/bash", "/app/start.sh"]

volumes:
  ollama_data: