version: "3.9"
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ollama-pull:
    image: ollama/ollama
    environment:
      - OLLAMA_HOST="ollama:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: "pull llama3.2:latest"

volumes:
  ollama_data: