name: Build and Release Electron App

on:
  push:
    tags:
      - "v*" # Runs only when pushing a tag like v1.0.0
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Package App
        run: npm run package

      - name: Make App
        run: npm run make

      - name: Debug Output
        run: ls -R out/make/ || echo "No files found!"

      - name: Rename and Move Artifacts for Release
        run: |
          mkdir -p release
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            if compgen -G "out/make/deb/x64/*.deb" > /dev/null; then
              mv out/make/deb/x64/*.deb release/
            fi
            if compgen -G "out/make/rpm/x64/*.rpm" > /dev/null; then
              mv out/make/rpm/x64/*.rpm release/
            fi
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv out/make/*.dmg release/grammar-corrector-macos.dmg
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            mv out/make/squirrel.windows/x64/MyAppInstaller.exe release/grammar-corrector-windows-x64.exe
          fi
        shell: bash

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: release/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download All Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "🚀 New release of Grammar Corrector! Download the installer for your OS below."
          draft: false
          prerelease: false
          files: release/**/*